version: '2.1'

volumes:
  iox_data: {}
  postgres_data: {}
  grafana_data: {}

services:
  iox:
    image: ghcr.io/metrico/influxdb-edge-musl:latest
    container_name: iox
    volumes:
      - ./data:/data
    environment:
      - INFLUXDB_IOX_OBJECT_STORE=file
      - INFLUXDB_IOX_DB_DIR=/data/db
      - INFLUXDB_IOX_BUCKET=iox
      - INFLUXDB_IOX_CATALOG_DSN=sqlite:///data/catalog.sqlite
      - INFLUXDB_IOX_WAL_DIRECTORY=/data/wal
      - INFLUXDB_IOX_ROUTER_HTTP_BIND_ADDR=iox:8080
      - INFLUXDB_IOX_ROUTER_GRPC_BIND_ADDR=iox:8081
      - INFLUXDB_IOX_QUERIER_GRPC_BIND_ADDR=iox:8082
      - INFLUXDB_IOX_INGESTER_GRPC_BIND_ADDR=iox:8083
      - INFLUXDB_IOX_COMPACTOR_GRPC_BIND_ADDR=iox:8084
      - INFLUXDB_IOX_COMPACTION_MEMORY_BUDGET_BYTES=3000000000
      - INFLUXDB_IOX_COMPACTION_MAX_COMPACTING_FILES=100
      - INFLUXDB_IOX_COMPACTION_MIN_ROWS_PER_RECORD_BATCH_TO_PLAN=32768
      - INFLUXDB_IOX_COMPACTION_MAX_DESIRED_FILE_SIZE_BYTES=104857600
      - INFLUXDB_IOX_COMPACTION_PERCENTAGE_MAX_FILE_SIZE=5
      - INFLUXDB_IOX_GC_OBJECTSTORE_SLEEP_INTERVAL_MINUTES=1
      - INFLUXDB_IOX_GC_PARQUETFILE_CUTOFF=30m
      - INFLUXDB_IOX_GC_OBJECTSTORE_CUTOFF=30m
      - LOG_FILTER=error
    restart: unless-stopped
    expose:
      - 8080
      - 8081
      - 8082
      - 8083
      - 8084
    ports:
      - 8080:8080
      - 8082:8082
      
  iox-gc:
    image: ghcr.io/metrico/influxdb-edge-musl:latest
    container_name: iox-gc
    build:
      dockerfile: ./Dockerfile
      context: .
    volumes:
      - ./data:/data
    environment:
      - INFLUXDB_IOX_OBJECT_STORE=file
      - INFLUXDB_IOX_DB_DIR=/data/db
      - INFLUXDB_IOX_BUCKET=iox
      - INFLUXDB_IOX_CATALOG_DSN=sqlite:///data/catalog.sqlite
      - INFLUXDB_IOX_COMPACTOR_GRPC_BIND_ADDR=iox:8084
      - INFLUXDB_IOX_COMPACTION_MEMORY_BUDGET_BYTES=3000000000
      - INFLUXDB_IOX_COMPACTION_MAX_COMPACTING_FILES=100
      - INFLUXDB_IOX_COMPACTION_MIN_ROWS_PER_RECORD_BATCH_TO_PLAN=32768
      - INFLUXDB_IOX_COMPACTION_MAX_DESIRED_FILE_SIZE_BYTES=104857600
      - INFLUXDB_IOX_COMPACTION_PERCENTAGE_MAX_FILE_SIZE=5
      - INFLUXDB_IOX_GC_OBJECTSTORE_SLEEP_INTERVAL_MINUTES=1
      - INFLUXDB_IOX_GC_PARQUETFILE_CUTOFF=1m
      - INFLUXDB_IOX_GC_OBJECTSTORE_CUTOFF=1m
      - LOG_FILTER=info
    restart: unless-stopped
    command:
      - /influxdb3
      - run
      - garbage-collector

  nginx:
    image: nginx:latest
    container_name: nginx_container
    volumes:
      - ./iox-nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8086:8086
    expose:
      - 8086
    depends_on:
      - iox

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    environment:
      - INFLUX_HOST=iox:8082
      - INFLUX_TOKEN=${INFLUXDB_TOKEN}
      - INFLUX_ORG=company
      - INFLUX_BUCKET=sensors
      - GF_INSTALL_PLUGINS=influxdata-flightsql-datasource
    volumes: 
      - ./demo/grafana/datasources:/etc/grafana/provisioning/datasources
#      - ./demo/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - grafana_data:/var/lib/grafana/
    restart: always
    depends_on:
      - iox
