volumes:
  iox_data: {}
  postgres_data: {}
  grafana_data: {}
  explorer_config:
  explorer_db:
  grafana-data:
    driver: local

services:
  iox:
    image: ghcr.io/metrico/influxdb3-unlocked:latest
    container_name: iox
    volumes:
      - ./data:/data
    environment:
      INFLUXDB3_MAX_HTTP_REQUEST_SIZE: "10485760"
      INFLUXDB3_GEN1_DURATION: "10m"
      INFLUXDB3_WAL_FLUSH_INTERVAL: "1s"
      INFLUXDB3_WAL_SNAPSHOT_SIZE: "600"
      INFLUXDB3_NUM_WAL_FILES_TO_KEEP: "50"
      INFLUXDB3_WAL_MAX_WRITE_BUFFER_SIZE: "100000"
      INFLUXDB3_BUFFER_MEM_LIMIT_MB: "5000"
      INFLUXDB3_PARQUET_MEM_CACHE_SIZE_MB: "1000"
      INFLUXDB3_FORCE_SNAPSHOT_MEM_THRESHOLD: "70%"
      INFLUXDB3_TELEMETRY_DISABLE_UPLOAD: true
      INFLUXDB3_NODE_IDENTIFIER_PREFIX: "iox-node1"
      INFLUXDB3_BUCKET: "iox"
      INFLUXDB3_OBJECT_STORE: "file"
      INFLUXDB3_DB_DIR: "/data"
    restart: unless-stopped
    ports:
      - 8082:8181
      - 8181:8181

  grafana:
    image: grafana/grafana-enterprise:latest # or a specific version like grafana/grafana:10.4.2
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000' # Maps host port 3000 to container port 3000
    volumes:
      - grafana-data:/var/lib/grafana # Persists Grafana data
    environment:
      - GF_SECURITY_ADMIN_USER=admin # Default admin user
      - GF_SECURITY_ADMIN_PASSWORD=secret # Default admin password (CHANGE THIS IN PRODUCTION)
      - GF_USERS_ALLOW_SIGN_UP=false # Disables user self-registration

  #   grafana:
  #     image: grafana/grafana:latest
  #     ports:
  #       - 3000:3000
  #     environment:
  #       - INFLUX_HOST=iox:8181
  #       - INFLUX_TOKEN=${INFLUXDB_TOKEN}
  #       - INFLUX_ORG=company
  #       - INFLUX_BUCKET=sensors
  #       - GF_INSTALL_PLUGINS=influxdata-flightsql-datasource
  #     volumes: 
  # #      - ./demo/grafana/datasources:/etc/grafana/provisioning/datasources
  # #      - ./demo/grafana/dashboards:/etc/grafana/provisioning/dashboards
  #       - grafana_data:/var/lib/grafana/
  #     restart: always
  #     depends_on:
  #       - iox
  influxdb3-explorer:
    image: influxdata/influxdb3-ui:latest
    container_name: influxdb3-explorer
    volumes:
      - explorer_db:/db:rw
    ports:
      - 8888:80
      - 8889:8888
    environment:
      DEFAULT_INFLUX_SERVER: "http://iox:8181"
      DEFAULT_SERVER_NAME: "iox:8181"
      DEFAULT_INFLUX_DATABASE: "__internal"
      DEFAULT_API_TOKEN: ${INFLUXDB_TOKEN}
    command: --mode=query
    restart: unless-stopped
    depends_on:
      iox:
        condition: service_started
