volumes:
  iox_data: {}
  postgres_data: {}
  grafana_data: {}

services:
  iox:
    image: ghcr.io/metrico/influxdb3-unlocked:latest
    container_name: iox
    volumes:
      - ./data:/data
    environment:
      INFLUXDB3_MAX_HTTP_REQUEST_SIZE: "10485760"
      INFLUXDB3_GEN1_DURATION: "10m"
      INFLUXDB3_WAL_FLUSH_INTERVAL: "1s"
      INFLUXDB3_WAL_SNAPSHOT_SIZE: "600"
      INFLUXDB3_NUM_WAL_FILES_TO_KEEP: "50"
      INFLUXDB3_WAL_MAX_WRITE_BUFFER_SIZE: "100000"
      INFLUXDB3_BUFFER_MEM_LIMIT_MB: "5000"
      INFLUXDB3_PARQUET_MEM_CACHE_SIZE_MB: "1000"
      INFLUXDB3_FORCE_SNAPSHOT_MEM_THRESHOLD: "70%"
      INFLUXDB3_TELEMETRY_DISABLE_UPLOAD: true
      INFLUXDB3_NODE_IDENTIFIER_PREFIX: "iox-node1"
      INFLUXDB3_BUCKET: "iox"
      INFLUXDB3_OBJECT_STORE: "file"
      INFLUXDB3_DB_DIR: "/data"
    restart: unless-stopped
    expose:
      - 8181
    ports:
      - 8086:8181
      - 8181:8181

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    environment:
      - INFLUX_HOST=iox:8082
      - INFLUX_TOKEN=${INFLUXDB_TOKEN}
      - INFLUX_ORG=company
      - INFLUX_BUCKET=sensors
      - GF_INSTALL_PLUGINS=influxdata-flightsql-datasource
    volumes: 
      - ./demo/grafana/datasources:/etc/grafana/provisioning/datasources
#      - ./demo/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - grafana_data:/var/lib/grafana/
    restart: always
    depends_on:
      - iox
