apiVersion: 1

datasources:
  - name: FlightSQL
    type: influxdata-flightsql-datasource
    typeName: FlightSQL
    access: proxy
    url: ''
    user: ''
    database: ''
    basicAuth: false
    isDefault: true
    jsonData:
      host: iox:8082
      metadata:
      - bucket-name: company_sensors
      - database: company_sensors
      secure: false
      token: ${INFLUX_TOKEN}
    readOnly: false
    editable: true
  - name: Flux
    type: influxdb
    uid: flux
    version: 2
    access: proxy
    url: http://fluxpipe:8086
    basicAuth: false
    jsonData:
      defaultBucket:
      httpMode: POST
      organization: iox
      version: Flux
    secureJsonData:
      token:
