name: Build iox

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build_iox_linux:
    name: ubuntu-20.04
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    steps:
      - name: Check out iox
        uses: actions/checkout@v3
        with:
          repository: influxdata/influxdb_iox
           
      - name: Log in to the GHCR registry
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Docker Build and push (server)
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: true
          tags: |
           ghcr.io/metrico/iox:latest
