name: Build iox musl

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build_iox_linux:
    name: ubuntu-20.04
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    steps:
      - name: Check out iox
        uses: actions/checkout@v3
        with:
          repository: influxdata/influxdb_iox
      - run: |
          echo "VERSION=${{  github.ref_name || "0.0.0" }}" >> $GITHUB_ENV
      - run: sudo apt update && sudo apt install -y musl-tools
      - name: Setup protoc
        uses: arduino/setup-protoc@v1.2.0
      - name: Cache Rust compilation
        uses: metalbear-co/sccache-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Optional, default is `sccache-`
          cache-from: sccache-${{ runner.os }}-
          # Optional, default is `sccache-latest`
          cache-to: sccache-${{ runner.os }}-${{ github.sha }}
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: x86_64-unknown-linux-musl

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-unknown-linux-musl
          
      - name: Check
        run: |
          find ./ -name influxdb_iox
          ldd ./target/x86_64-unknown-linux-musl/release/influxdb_iox
          
      - name: Compress Fluxpipe
        run: |
          strip ./target/x86_64-unknown-linux-musl/release/influxdb_iox
          upx ./target/x86_64-unknown-linux-musl/release/influxdb_iox
          
      - name: Upload release
        if: github.event_name != 'pull_request'
        uses: boxpositron/upload-multiple-releases@1.0.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_config: |
              ./target/x86_64-unknown-linux-musl/release/influxdb_iox
          tag_name: ${{ env.VERSION }}
          release_name: iox-musl_${{ env.VERSION }}
          draft: false
          prerelease: false
          overwrite: true   
